export const translateText = (text: string): string => {
  const dictionary: { [key: string]: string } = {
    'Hello': 'Hola',
    'World': 'Mundo',
    'News': 'Noticias',
    'Gaza': 'Gaza',
    'Israeli': 'Israelí',
    'war': 'guerra',
    'conflict': 'conflicto',
    'attack': 'ataque',
    'bombing': 'bombardeo',
    'ceasefire': 'alto el fuego',
    'peace': 'paz',
    'talks': 'conversaciones',
    'negotiations': 'negociaciones',
    'casualties': 'bajas',
    'injured': 'herido',
    'dead': 'muerto',
    'wounded': 'herido',
    'military': 'militar',
    'forces': 'fuerzas',
    'soldiers': 'soldados',
    'civilians': 'civiles',
    'children': 'niños',
    'women': 'mujeres',
    'men': 'hombres',
    'families': 'familias',
    'homes': 'hogares',
    'destroyed': 'destruido',
    'damaged': 'dañado',
    'humanitarian': 'humanitario',
    'aid': 'ayuda',
    'relief': 'alivio',
    'supplies': 'suministros',
    'food': 'comida',
    'water': 'agua',
    'medical': 'médico',
    'hospital': 'hospital',
    'doctors': 'doctores',
    'nurses': 'enfermeras',
    'volunteers': 'voluntarios',
    'donations': 'donaciones',
    'support': 'apoyo',
    'international': 'internacional',
    'community': 'comunidad',
    'leaders': 'líderes',
    'government': 'gobierno',
    'officials': 'funcionarios',
    'statements': 'declaraciones',
    'reports': 'informes',
    'updates': 'actualizaciones',
    'latest': 'último',
    'breaking': 'última hora',
    'developments': 'desarrollos',
    'situation': 'situación',
    'crisis': 'crisis',
    'emergency': 'emergencia',
    'response': 'respuesta',
    'efforts': 'esfuerzos',
    'progress': 'progreso',
    'challenges': 'desafíos',
    'obstacles': 'obstáculos',
    'solutions': 'soluciones',
    'strategies': 'estrategias',
    'plans': 'planes',
    'actions': 'acciones',
    'measures': 'medidas',
    'steps': 'pasos',
    'goals': 'objetivos',
    'objectives': 'objetivos',
    'outcomes': 'resultados',
    'results': 'resultados',
    'impact': 'impacto',
    'effects': 'efectos',
    'consequences': 'consecuencias',
    'implications': 'implicaciones',
    'analysis': 'análisis',
    'assessment': 'evaluación',
    'evaluation': 'evaluación',
    'findings': 'hallazgos',
    'conclusions': 'conclusiones',
    'recommendations': 'recomendaciones',
    'suggestions': 'sugerencias',
    'advice': 'consejo',
    'guidance': 'orientación',
    'information': 'información',
    'data': 'datos',
    'facts': 'hechos',
    'details': 'detalles',
    'evidence': 'evidencia',
    'proof': 'prueba',
    'documentation': 'documentación',
    'records': 'registros',
    'reports': 'informes',
    'studies': 'estudios',
    'research': 'investigación',
    'investigation': 'investigación',
    'examination': 'examen',
    'review': 'revisión',
    'survey': 'encuesta',
    'analysis': 'análisis',
    'assessment': 'evaluación',
    'evaluation': 'evaluación',
    'findings': 'hallazgos',
    'conclusions': 'conclusiones',
    'recommendations': 'recomendaciones',
    'suggestions': 'sugerencias',
    'advice': 'consejo',
    'guidance': 'orientación',
    'information': 'información',
    'data': 'datos',
    'facts': 'hechos',
    'details': 'detalles',
    'evidence': 'evidencia',
    'proof': 'prueba',
    'documentation': 'documentación',
    'records': 'registros',
    'reports': 'informes',
    'studies': 'estudios',
    'research': 'investigación',
    'investigation': 'investigación',
    'examination': 'examen',
    'review': 'revisión',
    'survey': 'encuesta',
    // Add more translations as needed
  };

  const words = text.split(' ');
  const translatedWords = words.map(word => {
    const lowerWord = word.toLowerCase();
    const translatedWord = dictionary[lowerWord];
    if (translatedWord) {
      return translatedWord.charAt(0).toUpperCase() + translatedWord.slice(1);
    }
    return word;
  });
  return translatedWords.join(' ');
};
